eureka:
  instance:
    appname: oauth2-server
    instance-id: oauth2-server
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: mysql
    username: root
    url: jdbc:mysql://127.0.0.1:3306/oauth2db
    name: oauth2db
    #connection pool config
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 4
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: default
server:
  port: 8888
security:
  ignored: /login
  user:
    name: user
    password: password